version: "3.8"
services:
  web:
    build:
      context: ./
      dockerfile: ./dispatcher/Dockerfile.fastapi
    ports:
      - 8004:8000
    command: poetry run uvicorn dispatcher.server:app --host 0.0.0.0
    environment:
      - CELERY_BROKER_URL=amqp://rabbitmq
      - CELERY_RESULT_BACKEND=dispatcher.backend:RCSDatabaseBackend+oracle://ADWGU_AXN:j3ezKQe_2021@azl-axnorcle01d.cloud-pg.com:1521/?service_name=axondev_pdb
    depends_on:
      rabbitmq:
        condition: service_started
  worker:
    build:
      context: ./
      dockerfile: ./dispatcher/Dockerfile.celery
    command: poetry run celery -A dispatcher.worker worker
    environment:
      - CELERY_BROKER_URL=amqp://rabbitmq
      - CELERY_RESULT_BACKEND=dispatcher.backend:RCSDatabaseBackend+oracle://ADWGU_AXN:j3ezKQe_2021@azl-axnorcle01d.cloud-pg.com:1521/?service_name=axondev_pdb
    depends_on:
      web:
        condition: service_started
      rabbitmq:
        condition: service_started
  rabbitmq:
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
